/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'alibi': {
          'violet':        '#7C3AED',
          'violet-light':  '#A78BFA',
          'violet-dark':   '#5B21B6',
          'violet-ghost':  'rgba(124,58,237,0.1)',
          'emerald':       '#10B981',
          'emerald-light': '#34D399',
          'emerald-ghost': 'rgba(16,185,129,0.1)',
          'bg':            '#0F0D1A',
          'bg-card':       '#1E1B2E',
          'bg-elevated':   '#2D2A40',
          'bg-hover':      '#3D3A50',
          'text':          '#E2E8F0',
          'text-muted':    '#94A3B8',
          'text-subtle':   '#64748B',
          'warning':       '#F59E0B',
          'error':         '#EF4444',
          'info':          '#3B82F6',
          'ai':            '#8B5CF6',
          'ai-light':      '#C4B5FD',
          'ai-ghost':      'rgba(139,92,246,0.1)',
          'border':        'rgba(45,42,64,0.8)',
          'border-light':  'rgba(61,58,80,0.8)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui'],
        mono: ['JetBrains Mono', 'ui-monospace'],
        display: ['Inter', 'ui-sans-serif'],
      },
      animation: {
        'pulse-slow':    'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-up':      'slideUp 0.3s ease-out',
        'fade-in':       'fadeIn 0.2s ease-out',
        'slide-in-right':'slideInRight 0.3s ease-out',
        'shimmer':       'shimmer 2s infinite linear',
        'float':         'float 6s ease-in-out infinite',
        'bounce-dot':    'bounceDot 1.4s ease-in-out infinite',
        'glow-pulse':    'glowPulse 2s ease-in-out infinite',
      },
      keyframes: {
        slideUp:    { '0%': { transform: 'translateY(12px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        fadeIn:     { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(12px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        shimmer:    { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float:      { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
        bounceDot:  { '0%, 80%, 100%': { transform: 'scale(0)' }, '40%': { transform: 'scale(1)' } },
        glowPulse:  { '0%, 100%': { boxShadow: '0 0 8px rgba(124,58,237,0.4)' }, '50%': { boxShadow: '0 0 20px rgba(124,58,237,0.8)' } },
      },
      boxShadow: {
        'glow-violet': '0 0 24px rgba(124, 58, 237, 0.4)',
        'glow-emerald': '0 0 24px rgba(16, 185, 129, 0.35)',
        'glow-ai': '0 0 20px rgba(139, 92, 246, 0.4)',
        'card': '0 4px 24px rgba(0, 0, 0, 0.4)',
        'elevated': '0 8px 40px rgba(0, 0, 0, 0.6)',
        'deep': '0 16px 64px rgba(0, 0, 0, 0.8)',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
};
