/**
 * @fileoverview Backend-specific constants that are not in @creative-alibi/shared.
 * These supplement the shared constants for backend-only logic.
 */

// ─── Report ───────────────────────────────────────────────────────────────────

export const REPORT_VERSION = '2.0.0';
export const REPORT_EXPIRY_DAYS = 365;
export const BADGE_BASE_URL = 'https://creative-alibi.app/badge';
export const REPORT_LEGAL_DISCLAIMER =
  'This report was generated by Creative Alibi™. It documents behavioral metadata ' +
  'collected during the writing session and does not constitute legal proof of authorship. ' +
  'All AI interaction disclosures are factual records of actual tool usage.';
export const AI_ASSIST_DISCLOSURE_TEXT =
  'Per Creative Alibi transparency standards, all AI interactions are logged and ' +
  'disclosed in full. AI suggestions were offered as options — the writer retained ' +
  'full editorial control.';

// ─── Ledger Thresholds ────────────────────────────────────────────────────────

export const MIN_TYPING_CADENCE_SCORE = 40;
export const MIN_REVISION_COUNT = 2;
export const MIN_SESSION_DURATION_SECONDS = 120;
export const MIN_WORD_COUNT_FOR_REPORT = 50;
export const MIN_AVERAGE_WPM = 5;
export const COMPOSITE_SCORE_WEIGHTS = {
  cadence: 0.35,
  pasteRatio: 0.25,
  revisions: 0.20,
  duration: 0.10,
  wpmConsistency: 0.10,
};

// ─── Detector ─────────────────────────────────────────────────────────────────

export const DESKLIB_MODEL_ID = 'desklib/ai-text-detector-v1.01';
export const HF_INFERENCE_URL = 'https://api-inference.huggingface.co/models';
export const DETECTOR_MAX_CALLS_PER_SESSION = 1;
export const DETECTOR_DISCREPANCY_THRESHOLD = 0.7;
export const DETECTOR_DISCLAIMER_TEXT =
  'This AI-likelihood estimate is informational only. It does not determine report eligibility. ' +
  'The Process Ledger is the sole determinant of authenticity.';

// ─── Ledger (duplicated from shared to avoid branded-type mismatch) ───────────
export const MAX_COPY_PASTE_RATIO = 0.20;

// ─── Granite / AI ────────────────────────────────────────────────────────────

export const GRANITE_TEMPERATURE_STYLE = 0.5;
export const GRANITE_TEMPERATURE_BRAINSTORM = 0.8;
export const GRANITE_TEMPERATURE_GRAMMAR = 0.2;
export const GRANITE_CONTEXT_MAX_CHARS = 200;

// ─── Granite Guardian ────────────────────────────────────────────────────────

export const GUARDIAN_REQUIRED_HEDGE_PHRASES = [
  'you might',
  'you could',
  'consider',
  'perhaps',
  'one option',
  'another approach',
  'for example',
  'what if',
];
export const GUARDIAN_MAX_SUGGESTION_WORDS = 80;
